import "./index.scss"

export default function Roadmap() {
  return (
    <div id="roadmap">
      <div className="h1s">
        <h1>ROADMAP</h1>
      </div>
      <h2>
      Join us on the journey to create the ultimate metaverse experience with SUIGALS - The Face of Sui!

        <br/>
        Be a part of the thriving Sui community!
        
        <br/>
            <br/>
        Owning a SuiGals NFT is akin to investing in a metaverse talent management company, allowing users to participate, invest, and co-develop the virtual idols' ownership. 
          <br/>
            <br/>
          NFT Holders will vote on creative and career development decisions, sharing in the revenue generated by NFTs and intellectual property.
          <br/>
            <br/>
          Simple words, it’s just like owning a piece of the SM Entertainment in the web3 world!

        
           </h2>
      <div className="list">
        <div className="line"/>
        <div className="item">
          <h1>Wave 1 - Genesis</h1>
          <h2>
          - Website & Social Media
          <br/>
- Genesis NFT Drop 
<br/>
- Community Building
<br/>
- Holder exclusive USDT & NFT giveaways

          </h2>
        </div>
        <div className="item">
          <h1>Wave 2 - Evolution </h1>
          <h2>
          - AIGC Music & MVs
<br/>

- Going Tiktok
<br/>

- Genesis-Holders Giveaways & Drops


          </h2>
        </div>
        <div className="item active">
          <h1>Wave 3 - Metaverse </h1>
          <h2>
          - Virtual Humans Ready

<br/>
- Major Metaverse Debut & Concerts
<br/>
- Monetizing the IPs
<br/>
- Merch Drops for Holders
          </h2>


        </div>
        <div className="item">
          <h1>Wave 4 - Protocol </h1>
          <h2>
          - Social gaming built on Sui
<br/>
- Native tokens as rewards for engagement
<br/>
- Avatar-based Sui-native DiD Protocol
<br/>
- AIGC Protocol: Create-to-Earn
          </h2>
        </div>
        <div className="item">
          <h1>Wave 5 - Intelligence </h1>
          <h2>
          - AI Virtual Idols
<br/>
- Huamn-level intelligence powered by GPT-5
<br/>
- Beyond our wildest imagination
<br/>

          </h2>
        </div>
      </div>
    </div>
  )
}